// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IncidentList The results of an incident history request
// swagger:model IncidentList
type IncidentList struct {

	// incidents
	Incidents IncidentListIncidents `json:"incidents"`

	// The limit value passed in the request
	Limit float64 `json:"limit,omitempty"`

	// The offset passed in the request
	Offset float64 `json:"offset,omitempty"`

	// The total number of incidents available for this search
	Total float64 `json:"total,omitempty"`
}

// Validate validates this incident list
func (m *IncidentList) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IncidentList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IncidentList) UnmarshalBinary(b []byte) error {
	var res IncidentList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
