// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ListTeamMembersResponse A list of members for the team
// swagger:model ListTeamMembersResponse
type ListTeamMembersResponse struct {

	// self Url
	SelfURL string `json:"_selfUrl,omitempty"`

	// team Url
	TeamURL string `json:"_teamUrl,omitempty"`

	// members
	Members ListTeamMembersResponseMembers `json:"members"`
}

// Validate validates this list team members response
func (m *ListTeamMembersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ListTeamMembersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListTeamMembersResponse) UnmarshalBinary(b []byte) error {
	var res ListTeamMembersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
