// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OnCallAndOverrides on call and overrides
// swagger:model OnCallAndOverrides
type OnCallAndOverrides struct {

	// overrides
	Overrides OnCallAndOverridesOverrides `json:"overrides"`

	// schedule
	Schedule OnCallAndOverridesSchedule `json:"schedule"`

	// team
	Team string `json:"team,omitempty"`
}

// Validate validates this on call and overrides
func (m *OnCallAndOverrides) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OnCallAndOverrides) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OnCallAndOverrides) UnmarshalBinary(b []byte) error {
	var res OnCallAndOverrides
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
