// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OnCallLog on call log
// swagger:model OnCallLog
type OnCallLog struct {

	// end
	End strfmt.DateTime `json:"end,omitempty"`

	// start
	Start strfmt.DateTime `json:"start,omitempty"`

	// team slug
	TeamSlug string `json:"teamSlug,omitempty"`

	// user logs
	UserLogs OnCallLogUserLogs `json:"userLogs"`
}

// Validate validates this on call log
func (m *OnCallLog) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OnCallLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OnCallLog) UnmarshalBinary(b []byte) error {
	var res OnCallLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
