// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PagingPolicyStep paging policy step
// swagger:model PagingPolicyStep
type PagingPolicyStep struct {

	// index
	Index float64 `json:"index,omitempty"`

	// rules
	Rules PagingPolicyStepRules `json:"rules"`

	// timeout
	Timeout TimeoutType `json:"timeout,omitempty"`
}

// Validate validates this paging policy step
func (m *PagingPolicyStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTimeout(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PagingPolicyStep) validateTimeout(formats strfmt.Registry) error {

	if swag.IsZero(m.Timeout) { // not required
		return nil
	}

	if err := m.Timeout.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("timeout")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PagingPolicyStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PagingPolicyStep) UnmarshalBinary(b []byte) error {
	var res PagingPolicyStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
