// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Policies Paging policies accociated which this user
// swagger:model Policies
type Policies struct {

	// policies
	Policies PoliciesPolicies `json:"policies"`

	// user Id
	UserID int64 `json:"userId,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this policies
func (m *Policies) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Policies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Policies) UnmarshalBinary(b []byte) error {
	var res Policies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
